# Generated by Django 5.2.6 on 2026-06-18 19:24

import uuid
from django.db import migrations, models


UUID_SQL = "(" \
    "substr(md5(random()::text || clock_timestamp()::text), 1, 8) || '-' || " \
    "substr(md5(random()::text || clock_timestamp()::text), 9, 4) || '-' || " \
    "substr(md5(random()::text || clock_timestamp()::text), 13, 4) || '-' || " \
    "substr(md5(random()::text || clock_timestamp()::text), 17, 4) || '-' || " \
    "substr(md5(random()::text || clock_timestamp()::text), 21, 12)" \
    ")::uuid"


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_orderitem_order_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=f"""
                        ALTER TABLE store_cart ADD COLUMN uuid_id uuid NOT NULL DEFAULT {UUID_SQL};
                        ALTER TABLE store_cartitem ADD COLUMN cart_uuid uuid;
                        UPDATE store_cartitem ci
                        SET cart_uuid = c.uuid_id
                        FROM store_cart c
                        WHERE ci.cart_id = c.id;
                        DO $$
                        DECLARE constraint_name text;
                        BEGIN
                            FOR constraint_name IN
                                SELECT conname
                                FROM pg_constraint
                                WHERE conrelid = 'store_cartitem'::regclass
                                  AND contype = 'f'
                            LOOP
                                EXECUTE format('ALTER TABLE store_cartitem DROP CONSTRAINT %I', constraint_name);
                            END LOOP;
                        END$$;
                        ALTER TABLE store_cartitem DROP COLUMN cart_id;
                        ALTER TABLE store_cart DROP CONSTRAINT store_cart_pkey;
                        ALTER TABLE store_cart DROP COLUMN id;
                        ALTER TABLE store_cart RENAME COLUMN uuid_id TO id;
                        ALTER TABLE store_cart ADD PRIMARY KEY (id);
                        ALTER TABLE store_cartitem RENAME COLUMN cart_uuid TO cart_id;
                        ALTER TABLE store_cartitem
                            ADD CONSTRAINT store_cartitem_cart_id_fk
                            FOREIGN KEY (cart_id) REFERENCES store_cart(id) ON DELETE CASCADE;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='cart',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]