# Generated by Django 5.2.6 on 2026-06-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
